# Generated by Django 4.2.7 on 2023-11-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acilan_Ders",
            fields=[
                ("AcilanDersID", models.AutoField(primary_key=True, serialize=False)),
                ("DersAdi", models.CharField(max_length=255)),
                ("Syllabus", models.TextField()),
                ("DersSaati1", models.TimeField(null=True)),
                ("DersSaati2", models.TimeField(null=True)),
                ("DersGunu", models.CharField(max_length=15, null=True)),
                ("DersKodu", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Aktif_Ogrenci",
            fields=[
                ("OgrenciID", models.AutoField(primary_key=True, serialize=False)),
                ("Ad", models.CharField(max_length=255)),
                ("Soyad", models.CharField(max_length=255)),
                ("Numara", models.CharField(max_length=9)),
                ("Tel", models.CharField(max_length=12)),
                ("Email", models.EmailField(max_length=254)),
                ("Adres", models.TextField()),
                ("GPA", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Ek_Gider",
            fields=[
                ("GiderID", models.AutoField(primary_key=True, serialize=False)),
                ("GiderAciklamasi", models.TextField()),
                ("GiderMiktari", models.IntegerField()),
                ("GiderTarihi", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Haftanin_Saatleri",
            fields=[
                ("SaatGunID", models.AutoField(primary_key=True, serialize=False)),
                ("BaslangicVakti", models.TimeField()),
                ("BitisVakti", models.TimeField()),
                ("Gun", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Idari_Personel",
            fields=[
                ("CalisanID", models.AutoField(primary_key=True, serialize=False)),
                ("Ad", models.CharField(max_length=255)),
                ("Soyad", models.CharField(max_length=255)),
                ("Adres", models.TextField()),
                ("Tel", models.CharField(max_length=12)),
                ("Email", models.EmailField(max_length=254)),
                ("Maas", models.FloatField()),
                ("BaslangicTarihi", models.DateField()),
                ("DeneyimSuresi", models.FloatField()),
                ("Unvan", models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Malzeme",
            fields=[
                ("MalzemeID", models.AutoField(primary_key=True, serialize=False)),
                ("MalzemeMiktari", models.IntegerField()),
                ("MalzemeFiyat", models.FloatField()),
                ("MalzemeTuru", models.TextField()),
                (
                    "GiderID",
                    models.ForeignKey(
                        db_column="GiderID",
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ek_gider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mezun_Ogrenci",
            fields=[
                ("OgrenciID", models.AutoField(primary_key=True, serialize=False)),
                ("Ad", models.CharField(max_length=255)),
                ("Soyad", models.CharField(max_length=255)),
                ("Numara", models.CharField(max_length=9)),
                ("Tel", models.CharField(max_length=12)),
                ("Email", models.EmailField(max_length=254)),
                ("Adres", models.TextField()),
                ("MezuniyetGPA", models.FloatField()),
                ("MezuniyetTarihi", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Ogretmen",
            fields=[
                ("CalisanID", models.AutoField(primary_key=True, serialize=False)),
                ("Ad", models.CharField(max_length=255)),
                ("Soyad", models.CharField(max_length=255)),
                ("Adres", models.TextField()),
                ("Tel", models.CharField(max_length=12)),
                ("Email", models.EmailField(max_length=254)),
                ("Maas", models.FloatField()),
                ("BaslangicTarihi", models.DateField()),
                ("DeneyimSuresi", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Sabit_Gider",
            fields=[
                ("GiderID", models.AutoField(primary_key=True, serialize=False)),
                ("GiderAciklamasi", models.TextField()),
                ("GiderMiktari", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Temizlik_Gorevlisi",
            fields=[
                ("CalisanID", models.AutoField(primary_key=True, serialize=False)),
                ("Ad", models.CharField(max_length=255)),
                ("Soyad", models.CharField(max_length=255)),
                ("Adres", models.TextField()),
                ("Tel", models.CharField(max_length=12)),
                ("Email", models.EmailField(max_length=254)),
                ("Maas", models.FloatField()),
                ("BaslangicTarihi", models.DateField()),
                ("DeneyimSuresi", models.FloatField()),
                ("CalismaYeri", models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Full_Time_Ogretmen",
            fields=[
                (
                    "CalisanID",
                    models.ForeignKey(
                        db_column="CalisanID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app.ogretmen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Part_Time_Ogretmen",
            fields=[
                (
                    "CalisanID",
                    models.ForeignKey(
                        db_column="CalisanID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app.ogretmen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Veli",
            fields=[
                ("VeliID", models.AutoField(primary_key=True, serialize=False)),
                ("VeliAdi", models.CharField(max_length=255)),
                ("VeliSoyadi", models.CharField(max_length=255)),
                ("VeliTel", models.CharField(max_length=12)),
                ("VeliEmail", models.EmailField(max_length=254)),
                (
                    "OgrenciID",
                    models.ForeignKey(
                        db_column="OgrenciID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.aktif_ogrenci",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Malzeme_Ders",
            fields=[
                ("MalzemeDersID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "AcilanDersID",
                    models.ForeignKey(
                        db_column="AcilanDersID",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.acilan_ders",
                    ),
                ),
                (
                    "MalzemeID",
                    models.ForeignKey(
                        db_column="MalzemeID",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.malzeme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ders",
            fields=[
                ("DersID", models.AutoField(primary_key=True, serialize=False)),
                ("DersAdi", models.CharField(max_length=255)),
                ("DersKodu", models.TextField(max_length=255)),
                (
                    "CalisanID",
                    models.ForeignKey(
                        db_column="CalisanID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ogretmen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aktif_Ogrenci_Mesguliyet",
            fields=[
                (
                    "AktifOgrenciMesguliyetID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Sebep", models.TextField()),
                (
                    "OgrenciID",
                    models.ForeignKey(
                        db_column="OgrenciID",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.aktif_ogrenci",
                    ),
                ),
                (
                    "SaatGunID",
                    models.ForeignKey(
                        db_column="SaatGunID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.haftanin_saatleri",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aktif_Ogrenci_Ders_Talep",
            fields=[
                (
                    "AktifOgrenciDersID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "DersID",
                    models.ForeignKey(
                        db_column="DersID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ders",
                    ),
                ),
                (
                    "OgrenciID",
                    models.ForeignKey(
                        db_column="OgrenciID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.aktif_ogrenci",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aktif_Ogrenci_Acilan_Ders_Alir",
            fields=[
                (
                    "AktifOgrenciAcilanDersID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "AcilanDersID",
                    models.ForeignKey(
                        db_column="AcilanDersID",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.acilan_ders",
                    ),
                ),
                (
                    "OgrenciID",
                    models.ForeignKey(
                        db_column="OgrenciID",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.aktif_ogrenci",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="acilan_ders",
            name="CalisanID",
            field=models.ForeignKey(
                db_column="CalisanID",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.ogretmen",
            ),
        ),
        migrations.AddField(
            model_name="acilan_ders",
            name="DersID",
            field=models.ForeignKey(
                db_column="DersID",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.ders",
            ),
        ),
        migrations.CreateModel(
            name="Part_Time_Ogretmen_Mesguliyet",
            fields=[
                (
                    "PartTimeOgretmenMesguliyetID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Sebep", models.TextField()),
                (
                    "SaatGunID",
                    models.ForeignKey(
                        db_column="SaatGunID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.haftanin_saatleri",
                    ),
                ),
                (
                    "CalisanID",
                    models.ForeignKey(
                        db_column="CalisanID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.part_time_ogretmen",
                    ),
                ),
            ],
        ),
    ]
