# Generated by Django 4.2.7 on 2023-11-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="full_time_ogretmen",
            name="CalisanID",
            field=models.OneToOneField(
                db_column="CalisanID",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="app.ogretmen",
            ),
        ),
        migrations.AlterField(
            model_name="ogretmen",
            name="CalisanID",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="part_time_ogretmen",
            name="CalisanID",
            field=models.OneToOneField(
                db_column="CalisanID",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="app.ogretmen",
            ),
        ),
    ]
